### ISSUE TITLE
Feature Request: Command permissions

### ISSUE THREAD

**Issue by mwmyoung** [DelxHQ/Soup#6]
For example, I would love to disable the /volume command for the default **everyone** group. One way I could see this being handled on the end-user side is: `/permission add|delete {soup.commandname} {group/role}` 
(this permission command would need to default to only admins)

..so as a server admin I would run '/permission delete soup.volume `@everyone`' 

I can see this being useful for other commands, and just in general is nice to keep as granular as possible.

**Comment by DelxHQ** [comment]
Closing this due to the new permissions manager implemented naively into Discord.
